spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: danglehuu.utc
    password: "gcee bauu sayv ychy"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
